#!/bin/bash

menu_src () {
bot_retorno="=========COMANDOS=========\n"
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
			 bot_retorno+="/ID (muestra sus ID)\n"
			 bot_retorno+="/menu (muestra este menu)\n"
			 bot_retorno+="/ayuda (muestra ayuda de los comandos)\n"
			 bot_retorno+="$LINE\n"
		 else
			 bot_retorno+="/ID (muestra sus ID)\n"
			 bot_retorno+="/Keygen (genera una key)\n"
			 bot_retorno+="/instal (link de instalacion)\n"
			 bot_retorno+="/menu (muestra este menu)\n"
			 bot_retorno+="/ayuda (muestra ayuda de los comandos)\n"
			 bot_retorno+="$LINE\n"
		 fi
	 else
		 unset PID_GEN
		 PID_GEN=$(ps x|grep -v grep|grep "http-server.sh")
		 [[ ! $PID_GEN ]] && PID_GEN=❌ || PID_GEN=✅
		 
		 bot_retorno+="/infosys (informacion del sistema)\n"
		 bot_retorno+="/ID (muestra sus ID)\n"
		 bot_retorno+="/add [id](añadir nuevas ID)\n"
		 bot_retorno+="/del [id](quitar un ID)\n"
		 bot_retorno+="/list (lista de ID permitidas)\n"
		 bot_retorno+="/Keygen (genera una key)\n"
		 bot_retorno+="/instal (link de instalacion)\n"
		 bot_retorno+="/power (online/offline) $PID_GEN\n"
		 bot_retorno+="/menu (muestra este menu)\n"
		 bot_retorno+="/ayuda (muestra ayuda de los comandos)\n"
		 bot_retorno+="/cache (Limpiar cache Ram)\n"
		 bot_retorno+="/update (actualiza el BotGen)\n"
		 bot_retorno+="/reboot (Reinicia el servidor vps)\n"
		 bot_retorno+="$LINE\n"
	 fi	
msj_fun
}
